name: pterodactyl_app
description: A Pterodactyl Mobile App.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.3.8+54
authors:
  - Ruben Talstra <rubentalstra1211@outlook.com>
  - Yvan Watchman <ywatchman@cyberfusion.nl>

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: any              # any is love <3
  http: any                         # any is love <3
  convert: any                      # any is love <3
  flutter_sparkline: any            # any is love <3
  flutter_staggered_grid_view: any  # any is love <3
  shared_preferences: any           # any is love <3
  flutter_cupertino_settings: any   # any is love <3
  font_awesome_flutter: any         # any is love <3
  dynamic_theme: any                # any is love <3
  get_version: any                  # any is love <3
  firebase_messaging: any           # any is love <3
  url_launcher: any                 # any is love <3
  firebase_remote_config: any       # any is love <3
  adhara_socket_io: any             # any is love <3
  simple_gravatar: any              # any is love <3
  flutter_speed_dial: any           # any is love <3
  titled_navigation_bar: any        # any is love <3
  division: any                     # any is love <3
  responsive_container: any         # any is love <3
  logger: any                       # any is love <3
  photo_view: any                   # any is love <3
  pinput: any                       # any is love <3
  timeago: any                      # any is love <3


  dbutils:
    git:
      url: git://github.com/AndriousSolutions/dbutils.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/images/pterodactyl_icon.png
   - assets/lang/en-US.json
   - assets/lang/en-UK.json
   - assets/lang/de-DE.json
   - assets/lang/fr-FR.json
   - assets/lang/nl-NL.json
   - assets/lang/da-DK.json
   - assets/lang/nn-NO.json
   - assets/lang/pl-PL.json
   - assets/lang/it-IT.json
   - assets/lang/se-SE.json
   - assets/lang/zh-CN.json
   - assets/lang/zh-TW.json
   - assets/lang/si-SI.json
   - assets/lang/es-ES.json
   - assets/lang/id-ID.json
   - assets/lang/ar-AE.json
   - assets/lang/he-IL.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
